"""changed nullable fields to not nullable

Revision ID: 1f658434dfa2
Revises: f8c4ce01c4a0
Create Date: 2024-02-27 20:22:31.064254

"""
import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f658434dfa2'
down_revision = 'f8c4ce01c4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'categories',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('books', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('books', 'publication_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('books', 'publisher',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('books', 'isbn',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('books', 'language',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('books', 'page_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('books', 'electronic_format',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('books', 'electronic_size',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('books', 'protection_method',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('books', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('books', 'currency',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('books', 'image_url',
               existing_type=mysql.VARCHAR(length=768),
               nullable=False)
    op.alter_column('books', 'image_filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'image_filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('books', 'image_url',
               existing_type=mysql.VARCHAR(length=768),
               nullable=True)
    op.alter_column('books', 'currency',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('books', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('books', 'protection_method',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('books', 'electronic_size',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('books', 'electronic_format',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('books', 'page_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('books', 'language',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('books', 'isbn',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('books', 'publisher',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('books', 'publication_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('books', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('books', 'categories',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
