"""initial migration

Revision ID: 472c32b5bf08
Revises: 
Create Date: 2024-02-28 13:55:59.495745

"""
import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision = '472c32b5bf08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
