"""changed nullable fields to not nullable

Revision ID: 497c610fdb7a
Revises: 1f658434dfa2
Create Date: 2024-02-27 20:36:23.787525

"""
import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision = '497c610fdb7a'
down_revision = '1f658434dfa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
